[workspace]

[package]
name = "zs-webauthn-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_json = "1"
base64 = "0.22"

[dependencies.zs-webauthn]
path = ".."

[dependencies.zs-crypto]
path = "../../zs-crypto"

[[bin]]
name = "attestation_parser"
path = "fuzz_targets/attestation_parser.rs"
test = false
doc = false
bench = false
