//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// AccessRequestBody defines model for AccessRequestBody.
type AccessRequestBody struct {
	Approvals *[]Approval `json:"approvals,omitempty"`

	// ExpectedAuthorityDomain Domaine d'autorité attendu pour la vérification des approbations.
	ExpectedAuthorityDomain string   `json:"expected_authority_domain"`
	Justification           string   `json:"justification"`
	Posture                 *Posture `json:"posture,omitempty"`
	Resource                Resource `json:"resource"`
	SourceNetwork           *string  `json:"source_network,omitempty"`
	TicketRef               string   `json:"ticket_ref"`

	// Verb Examples: db.connect
	Verb string `json:"verb"`
}

// Approval defines model for Approval.
type Approval struct {
	// ApprovedAt Horodatage DÉCLARÉ par l'appelant, pas vérifié (ADR-017) — identity.v1. VerifyAssertionResponse ne renvoie pas d'horodatage vérifié pour l'assertion.
	ApprovedAt time.Time `json:"approved_at"`

	// Assertion Assertion identity-assertion/v1 scellée (base64) de l'approbateur.
	Assertion []byte `json:"assertion"`
}

// Decision defines model for Decision.
type Decision struct {
	Allowed              bool    `json:"allowed"`
	DecisionHash         *[]byte `json:"decision_hash,omitempty"`
	LeaseDurationSeconds *int    `json:"lease_duration_seconds,omitempty"`

	// LeaseId Présent seulement si allowed = true ET que l'émission via credential-issuer a réussi (backlog L2.4 suite) — absent si l'émission a échoué (indisponibilité OpenBao) même quand la décision elle-même est ALLOW ; le client doit distinguer "refusé" d'"autorisé mais rien n'a pu être émis".
	LeaseId       *string  `json:"lease_id,omitempty"`
	PolicyVersion *string  `json:"policy_version,omitempty"`
	Reasons       []string `json:"reasons"`
}

// Error defines model for Error.
type Error struct {
	Reason string `json:"reason"`
}

// Posture defines model for Posture.
type Posture struct {
	AgentVersion  *string    `json:"agent_version,omitempty"`
	DiskEncrypted *bool      `json:"disk_encrypted,omitempty"`
	EvaluatedAt   *time.Time `json:"evaluated_at,omitempty"`
	Managed       *bool      `json:"managed,omitempty"`
}

// Resource defines model for Resource.
type Resource struct {
	Attributes      *map[string]string `json:"attributes,omitempty"`
	AuthorityDomain string             `json:"authority_domain"`
	Id              string             `json:"id"`
	Type            string             `json:"type"`
}

// CreateAccessRequestParams defines parameters for CreateAccessRequest.
type CreateAccessRequestParams struct {
	// XIdentityAssertion Assertion identity-assertion/v1 scellée (base64) du demandeur.
	XIdentityAssertion []byte `json:"X-Identity-Assertion"`
}

// CreateAccessRequestJSONRequestBody defines body for CreateAccessRequest for application/json ContentType.
type CreateAccessRequestJSONRequestBody = AccessRequestBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateAccessRequest Ouvre une demande d'accès JIT et retourne la décision du PDP.
	// (POST /v1/access-requests)
	CreateAccessRequest(w http.ResponseWriter, r *http.Request, params CreateAccessRequestParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateAccessRequest operation middleware
func (siw *ServerInterfaceWrapper) CreateAccessRequest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateAccessRequestParams

	headers := r.Header

	// ------------- Required header parameter "X-Identity-Assertion" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Identity-Assertion")]; found {
		var XIdentityAssertion []byte
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Identity-Assertion", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Identity-Assertion", valueList[0], &XIdentityAssertion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "byte"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Identity-Assertion", Err: err})
			return
		}

		params.XIdentityAssertion = XIdentityAssertion

	} else {
		err := fmt.Errorf("Header parameter X-Identity-Assertion is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Identity-Assertion", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccessRequest(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/access-requests", wrapper.CreateAccessRequest)

	return m
}
